### ISSUE TITLE
Syntax error on 'import egoi-api'

### ISSUE THREAD

**Issue by richardfogaca** [E-goi/sdk-python#1]
The dash is causing a syntax error when trying to import the package.

![Screenshot from 2021-02-12 17-04-18](https://user-images.githubusercontent.com/63572350/107819950-c1bef900-6d58-11eb-810e-3b7c94ae0a81.png)

**Comment by renato-gomes** [comment]
Hi,
Please check if Version: 1.1.2RC1 solves your problem.
